- includes/validate.php
Fixes #3 and #5
The wrapper function `file_get_html` for `simple_html_dom` can return false.  This was resulting in `edac_get_content` having three possible return types bool(false), an empty array, or the simple_html_dom object.  I refactored this to only return false or the object. This allows bailing from `edac_validate` if the content cannot be retrieved.
> ensure that rules are not run if content not retrieved

- includes/rules/color_contrast_failure.php
Uses `! is_empty()` to test the `$found_value` variable. Empty includes `isset()` functionality so it will not throw an error if the variable is undefined.
fixes https://github.com/equalizedigital/accessibility-checker/issues/82
> fix undefined variable error

- includes/rules/video_present.php
There were a few additional approaches to this problem that I considered. However, I ultimately chose the most readable solution that maintained the current algorithm's complexity. Implementing other approaches would have required significant refactoring, which I believe was not the main intent of this task.
Please note that there are a couple of minor edge cases not addressed in the current implementation:
1. The first one is having the same video embedded twice with different YouTube URLs (e.g., `youtube.com/foo` and `youtu.be/foo`). While this issue may not arise with Gutenberg, it could potentially occur with other builders. For now, I don't recommend complicating the code with URL normalization, but it's something to keep in mind for future improvements.
2. Another minor edge case is …
> fixed - a video is present duplicated warning issue

- includes/rules/missing_headings.php
I have added the minimum word count and professional version requirements.
**Some stuff worth considering:**
- If we might have similar word-limiting occasions this should be pulled out to a helper function. 
- I did not have access to a valid key at the time of testing, so I wasn't able to conduct a thorough test. This pro check should properly work though. Also regarding the check for professional plugin version rules, I suggest that it be implemented separately from the rule-checking functions. One possible solution would include the key with a boolean value for each rule within an individual rule array, in the `edac_register_rules()` function. However, this might make it easy to crack/null the plugin but that is for a different discussion. 
My general suggestion is to deal with the …
> feature - missing subheadings check requirements

- accessibility-checker.php
- includes/options-page.php
This PR:
- Adds "Never" as an option for "Prompt for Simplified Summary" and updates description [[Ref]](https://github.com/equalizedigital/accessibility-checker/blob/8758ce833378ac4e9652f2ec157d191fcddb06cc/includes/options-page.php#L297-L301) [[Ref]](https://github.com/equalizedigital/accessibility-checker/blob/8758ce833378ac4e9652f2ec157d191fcddb06cc/includes/options-page.php#L311-L315)
- Adds logic so that when Prompt for Simplified Summary is set to Never:
- the Simplified Summary will not show on the post/page, even if one has been previously set [[Ref]](https://github.com/equalizedigital/accessibility-checker/blob/c2903df2c7e7add8e2af6579c97572c31679d736/accessibility-checker.php#L1550-L1553) 
- the summary tab will warn that a Simplified Summary will not be included on the …
> Prompt for Simplified Summary: add option for 'never'

- includes/rules/img_alt_long.php
100 characters doesn't feel long enough for quality image alt on many photos or graphics. Increasing this to 300 characters or only about a small bit longer than a tweet.
This feels like an improvement to this rule after seeing some longer alt on client sites that I still think is good alt.
> Increase max characters in alt

- accessibility-checker.php
- Removes commented out code
- Cast $summary['readability'] from a string to an integer so <= comparison is correct
- Logic fix
> Fixes #185

- includes/helper-functions.php
Helper function edac_remove_elements failed to check if dom was empty before trying to remove elements.
> 279 edac_remove_elements fails if dom is empty

- includes/classes/class-issues-query.php
- includes/classes/class-rest-api.php
- includes/classes/class-scans-stats.php
- includes/classes/class-settings.php
- includes/classes/class-widgets.php
- includes/options-page.php
- src/admin/index.js
- [Correct the error](#308) on the widget and welcome screens.
- Show a notice on the widget if there are no pages set to be scanned.
- Cache widget scan stats for 5 minutes.
- Clear the cached scan stats when the selected page types are changed or when a full scan is completed.
Notice shown if no pages are set to be scanned:
Widget after the selected pages types are changed but before a scan:
Welcome after the selected pages types are changed but before a scan:
> Fixes #308

- accessibility-checker.php
- includes/activation.php
- includes/validate.php
Calling `add_option` is in most cases unnecessary. In this PR we're just cleaning up these calls.
> Remove calls to add_option and replaces it with update_option where appropriate

- accessibility-checker.php
- includes/classes/class-admin-notices.php
- includes/classes/class-welcome-page.php
- includes/classes/class-widgets.php
- includes/deprecated.php
- includes/enqueue-scripts.php
- includes/helper-functions.php
- includes/system-info.php
- includes/validate.php
- partials/welcome-page.php
The `edac_check_plugin_active` function is a simple alias of the `is_plugin_active` function.
This PR deprecates the function by doing the following:
* Added a new `includes/deprecated.php` file and included it.
* Moved the `edac_check_plugin_active` function there, simplified it, and added a `_deprecated_function` call inside it to warn developers that the function was deprecated in v1.6.10 (we can tweak the version number depending on when this PR gets merged and what the next version will be)
* Replaced all calls to `edac_check_plugin_active` with `is_plugin_active`
> Deprecate the `edac_check_plugin_active` function

- includes/classes/class-admin-notices.php
- tests/phpunit/test-admin_notices.php
This PR removes hooks from the constructor of `EDAC\Admin_Notices` and adds basic unit tests.
- Added `init_hooks` method to the `EDAC\Admin_Notices` class.
- Moved hooks out of the constructor
- Created `test-admin_notices.php` unit test that tests for returned strings and expected messages.
#395
> Fix/admin notice constructor #395

- includes/helper-functions.php
- tests/phpunit/helper-functions/test-edac_ordinal.php
The `edac_ordinal` function was using hardcoded logic to determine the ordinal format of numbers.
This presented the following challenges:
* Ordinals were only valid for the `en_US` locale
* Even in the `en_US` locale, big numbers were not properly formatted. For example it should be `99,701st` and not `99701st`
* There were no safeguards in case the input was improper (an invalid string, a float and so on)
This PR removed the hardcoded logic and now uses PHP's `NumberFormatter`, passing the WP locale to it, and typecasting the input to an integer.
I also added a lot of tests for this function, accounting for invalid inputs, different locales etc.
> Refactor the `edac_ordinal` function

- accessibility-checker.php
When adding a variable directly in an included file, it becomes accessible to all of WP.
So this:
```php
$foo = 'bar';
```
is like this:
```php
global $foo;
$foo = 'bar';
```
Unless that's what we want to do, we should avoid doing it because it might override some other global variable set by another plugin/theme/WP.
> Avoid setting a `$plugin_check` global variable

- accessibility-checker.php
Similar to #420.
This PR moves the logic to include rules files inside an `edac_include_rules_files` function, and then calls that function.
This will avoid conflicts with other plugins that may set a `$rules` global variable.
> Avoid setting a `$rules` global variable

- accessibility-checker.php
This PR contains minor tweaks in the main plugin file:
* Split long lines to multiple lines where appropriate
* Removed a couple of unnecessary variables
* Removed calls to `add_post_meta` before `update_post_meta`
* Simplified a couple of conditions
* Fixed some translations
> Improve code-quality/readability in the main file

- includes/validate.php
This PR:
Replaces array_merge with array_merge_recursive because $context_opts and $default_context_opts are multi-dimensional.
> Fixes #425

- .editorconfig
- .eslintrc
- .github/workflows/lint-js.yml
- .github/workflows/lint-php.yml
- package-lock.json
- package.json
- src/admin/index.js
- src/app/index.js
- src/app/scanner/checks/always-fail.js
- src/app/scanner/index.js
- src/app/scanner/rules/color-contrast-failure.js
- src/app/scanner/rules/custom-rule-1.js
- webpack.config.js
Fixes #370 
This PR does the following:
* Adds a linter for JS
* Fixes the JS Coding-Standards issues that were reported
* Adds a GitHub workflow to automatically run the JS Linter on pull-requests
> Add JS linter and fix reported issues

- admin/class-issues-query.php
- admin/class-rest-api.php
- includes/validate.php
The `EDAC\Helpers` class was recently renamed to `EDAC\Admin\Helpers`. However, there were still a few instances where we called `EDAC\Helpers`, and the result was a fatal error: `PHP Fatal error:  Uncaught Error: Class "EDAC\Helpers" not found`.
This PR renames the remaining instances of `EDAC\Helpers`
> EDAC\Helpers was renamed to EDAC\Admin\Helpers

- includes/validate.php
I noticed a couple of calls to an `edac_log` function. However, that function does not exist anywhere.
I found `edacp_log` - and I _assume_ that is the one we wanted to use, so I renamed the calls to the right function.
> The `edac_log` function does not exist

- accessibility-checker.php
- admin/class-ajax.php
- includes/validate.php
From the documentation of the [`update_post_meta`](https://developer.wordpress.org/reference/functions/update_post_meta/) function:
> If the meta field for the post does not exist, it will be added and its ID returned.
> 
> Can be used in place of [add_post_meta()](https://developer.wordpress.org/reference/functions/add_post_meta/) .
This PR removes calls to `add_post_meta` and uses `update_post_meta` where appropriate.
This will also ensure that post-meta will properly get updated (if the post-meta already exists, `add_post_meta` does not update the value)
> Remove unnecessary calls to add_post_meta

- admin/class-ajax.php
Recently, the namespace of the `Admin_Notices` class changed.
There was an instance where we were still using the old namespace, throwing errors
> `\EDAC\Admin_Notices` changed to `\EDAC\Admin\Admin_Notices`

- includes/helper-functions.php
- includes/rules/broken_aria_reference.php
- includes/rules/missing_transcript.php
This PR changes some errors in docblock param & return types.
Additionally, the `edac_str_get_html` function can return either an object or false, so a condition was added to ensure we don't call methods on a false variable.
> Fix docblock types & add an extra condition

- includes/system-info.php
Nested ternary expressions (without parentheses) deprecated in PHP 7.4. Targeting PHP 8.3.0.
> Fix PHP deprecation for nested ternary expressions

- admin/class-frontend-highlight.php
In a file with `EDAC\Admin` namespace, we're calling the `WP_Error` class.
This PR changes these calls to `\WP_Error` because otherwise we'll get errors since the class is not in our namespace.
> `WP_Error` is not in our namespace

- .eslintrc
- src/admin/index.js
- src/app/index.js
- src/app/scanner/index.js
- webpack.config.js
In #424 we fixed the important stuff in JS.
This PR is a 2nd pass, doing the following changes:
* Changed `@wordpress/eslint-plugin/recommended` to `@wordpress/eslint-plugin/esnext` in our ESLint configuration
* Added global variables in the ESLint config so we don't need to define them per-file/line
* Fixed new reported issues
* Replaced `edac_script_vars` with `edacScriptVars` where possible (defined it as a const in the beginning of files with `const edacScriptVars = edac_script_vars;`). This allowed us to get rid of many eslint-disable lines.
* In some places changed concatenation from using `+` to using backticks. This made some things easier to read, and for printed text it will make i18n easier at a later date (right now, text in JS is not translatable, but we can change that in a …
> JS Coding Standards fixes - 2nd pass

- tests/phpunit/test-simplified_summary.php
This PR adds unit tests that test the output of the simplified_summary_markup with and without a summary.
> Simplified Summary Unit Tests

- accessibility-checker.php
- includes/classes/class-helpers.php
- includes/enqueue-scripts.php
- includes/options-page.php
- includes/validate.php
- src/editorApp/checkPage.js
- src/editorApp/index.js
This PR:
- Bugfix: changes misnamed js variable from edacp_full_site_scan_app to edacpFullSiteScanApp
- Adds EDAC\Helpers\is_basic_auth()
- replaces get_option( 'edac_password_protected') checks with EDAC\Helpers\is_basic_auth() 
- Adds basicAuth to js edac_editor_app
- Adds auth warning to editor page when user saves a post in free on a site that requires auth
> Hotfix - basic auth fix

- src/editorApp/checkPage.js
The PR:
- Exits the listener for editor saves when core/editor is not defined
Before fix:
- <img width="1065" alt="Screenshot 2024-01-12 at 1 36 40 PM" src="https://github.com/equalizedigital/accessibility-checker/assets/695220/c05707cb-11c2-4a0c-b07f-bba4b5456088">
- <img width="657" alt="Screenshot 2024-01-12 at 1 36 55 PM" src="https://github.com/equalizedigital/accessibility-checker/assets/695220/86300ee6-6485-4483-9c1e-6d4d4ce7e58a">
After fix:
- No core/editor related console errors
- <img width="629" alt="Screenshot 2024-01-12 at 1 37 26 PM" src="https://github.com/equalizedigital/accessibility-checker/assets/695220/c52cc255-11f3-499a-a5d1-fb420c9cba28">
> Bugfix: Classic editor conflict

- accessibility-checker.php
- includes/classes/class-helpers.php
- includes/classes/class-scans-stats.php
- includes/enqueue-scripts.php
- src/editorApp/index.js
This PR fixes https://github.com/equalizedigital/accessibility-checker-pro/issues/186
- Removes unreliable server side check for determining if site is password protected
- Removes js-based password protected warnings
- Fixes PHP Deprecated:  Automatic conversion of false to array is deprecated in /var/www/html/wp-content/plugins/accessibility-checker/includes/classes/class-scans-stats.php on line 440
> Auth issue fix

- includes/rules/incorrect_heading_order.php
This PR corrects false positives on the incorrect heading order rule.
See: 
https://equalizedigital.zendesk.com/agent/tickets/6229
https://equalizedigital.zendesk.com/agent/tickets/6226
Before:
After:
> Hotfix for incorrect heading order issue

- admin/class-ajax.php
This PR updates the simplified summary readability grade-level logic.
- Fixed issue with trying to compare the simplified summary ordinal value
- Removed `wp_send_json_error()` from `simplified_summary` Ajax function when the simplified summary is empty
- Added simplified summary grade-level, message, and icon logic to the `summary()` Ajax
- See functionality screenshots on issue: https://github.com/equalizedigital/accessibility-checker/issues/482#issuecomment-1933389399
Fixes: #482
> Simplified summary readability logic #482

- admin/class-ajax.php
This PR fixes the issue with the submit button text showing as `Submit Query` in Firefox.
Fixes: #481
> Added value to simplified summary submit button #481

- includes/rules/missing_transcript.php
The PR fixes the issue with the missing transcript rule flagging false positives on `mailto:` links and other like types.
- Added conditional to skip certain types of links
Fixes #400
> Updated  missing transcript rule to skip certain types of links

- accessibility-checker.php
- includes/classes/class-frontend-validate.php
- includes/classes/class-plugin.php
- tests/phpunit/test-frontend-validate.php
The PR refactors the edac_before_page_render into a new class with unit tests.
- Removed: edac_before_page_render functions from the main file
- Added: frontend validate class
- Added: frontend validate unit tests
Fixes: #472
> Frontend Validate Class

- accessibility-checker.php
- admin/class-frontend-highlight.php
- admin/class-helpers.php
- readme.txt
- src/frontendHighlighterApp/index.js
When someone filters out a certain rule after a page is scanned, the Ajax call still returns those rules to the highlighter in a 'null' state without any information. This PR seeks to not return null data to the highlighter so they are not shown on the frontend when inspecting the page issues.
* Prevent filtered out rule issues being passed down to the highlighter.
* Also disable the buttons in the highlighter until we know we have issues to display.
<details>
<summary>Widget when loading doesn't show nav buttons anymore</summary>
</details>
<details>
<summary>Show buttons only after we know there are issues to display</summary>
</details>
<details>
<summary>Show no buttons when no issues were returned from ajax call</summary>
</details>
Fixes #524
> Solve some unexpected situations with frontend highlighter when rules are filtered off

- src/common/helpers.js
- webpack.config.js
Refactors the inclusion of notyf styles to pull from the already installed notyf package and have it bundled into a local CSS file for inclusion.
Fixes: #510
> Don't load notyf styles from CDN

- includes/classes/class-edac-dom.php
- tests/phpunit/includes/rules/MissingTranscriptTest.php
The missing transcript rule can detect a false positive when the URL of a site or domain contains one of the extensions it tries to match against. Eg: www.wma.com
This PR attempts to avoid those by shifting the check to match against only the EXTENSION of href values and not matching within the value. That might not be the right approach, but pushing this up as an early attempt will add more tests to validate it suits and doesn't break any existing content checking that should pass (or allow some that should fail).
Fixes: #511
> Tweak missing_transcript rule to try to avoid some false positives

- includes/rules/aria_hidden.php
- tests/phpunit/includes/rules/AriaHiddenTest.php
Right now, the aria-hidden rule flags a warning for every instance that it detects and tasks users with looking at each one and its context to determine whether it is valid. If they find it valid, they are instructed to ignore the issue.
This PR seeks to add some smarts to the checker so that it can try not to flag some instances as warnings when we can tell they are valid already.
It was pretty easy to detect items with labels on the parent, but screen reader text and visible text are a little more challenging and are still being worked through.
* Unit tests have been added to try to cover all the new functionality
Closes: #448
> Improve aria-hidden warning rule to cover some valid use cases for adding it to elements

- includes/validate.php
This is a first pass at a solution for #535 . It returns from the save method when the post is trashed to avoid it, resulting in request errors later in the chain.
Bailing early here ensures that the rest of the flow runs and the data is purged.
There may be a better solution to this, but I haven't found anything as simple as this. I will continue to think and find something more robust if I can.
Resolves: #535
> Short-circuit edac_save_post() when post_status is trash

- includes/classes/class-frontend-validate.php
- readme.txt
Adds a catch inside the Frontend_Validate classes validate method to return before attempting to validate if the post is an auto-draft.
Fixes: #539
> Auto draft causing error attempting scan not-existing page

- admin/class-enqueue-admin.php
- composer.json
- includes/classes/class-enqueue-frontend.php
- includes/rules/empty_button.php
- includes/rules/img_alt_empty.php
- includes/rules/img_alt_missing.php
- includes/rules/text_small.php
The latest WPCS update caused a new rule to run on our code to enforce clarifying parenthesis. That is a good rule so I fixed the issues flagged instead of disabling it.
I also took the opportunity to space out those changed conditions to improve readability while I was clarifying them with parenthesis.
Closes: #546
> Fix missing clarifying parenthesis cs check

- includes/classes/class-summary-generator.php
- includes/helper-functions.php
- includes/validate.php
- tests/phpunit/includes/SummaryGeneratorTest.php
When certain validation errors occur a default density_data meta value is created as a string of `'0,0'` but when the data is processed it expects it to be an array. 
* Updates those places in the validation method to use an array of `[ 0, 0 ]` so it matches what is expected when processing.
* Adds some additional checks before processing or accessing it to ensure it is an array.
* Adds a test case that validates the issue is fixed
Fixes: #548
> Check we have an array before accessing it when producing density to return via ajax

- includes/rules/missing_form_label.php
This PR fixes the strict comparison issue within the missing form label rule that prevented it from returning issues.
Fixes #543
> Missing form label rule strict comparison fix

- includes/rules/img_alt_long.php
- tests/phpunit/EDACRuleImgAltLongTest.php
This PR adds a filter to control the max alt length and unit tests for the image alt long rule.
- Added: `edac_rule_img_alt_long` filter that defaults to `300`
- Added: unit test for the `edac_rule_img_alt_long` function
- Test that function returns an empty array when all images have alt text within the allowed length
-  Test that function returns an array with errors when images have alt text longer than the allowed length
-  Test that the filter modifies the maximum allowed alt text length
Fixes #95
> added - edac_max_alt_length filter and edac_rule_img_alt_long tests #95

- scripts/prep_release.sh
It fetches changes, updates local branches it operates on, creates a new branch and bumps the version in several places. Creates a list of PRs merged since last release and provides a link to open the PR against main with a pre-filled title.
Run it from the root of the repo with `./scripts/prep_release.sh patch` where the bump can be either major, minor or patch.
This is the output from my last test (ignore the silly version numbers, that was just for testing).
``` bash
Getting plugin version from accessibility-checker.php
Current version: 34.5.9
Bumping to version: 34.5.10
Creating release branch
M       scripts/dist.sh
Switched to branch 'develop'
Your branch is up-to-date with 'origin/develop'.
Already up-to-date.
Switched to a new branch 'release/34.5.10'
Updating version in files
> …
```
> Add a new script to help prep releases

- admin/class-ajax.php
- admin/class-update-database.php
- admin/site-health/class-free.php
- admin/site-health/class-pro.php
- includes/classes/class-summary-generator.php
- includes/options-page.php
- includes/validate.php
This PR wraps many places where we store or output data in sanitisers, validators, or escapes.
I don't generally think any of these places or pieces of data would have been a risk, but adding this as a precaution is still worth it.
I searched the code with regex and looked at every instance of `(set|update|add)_(option|post_meta|transient)` to find these location
Fixes: #509
> Improve data and input handling for storage

- .github/workflows/deploy-on-release-to-dot-org.yml
- .github/workflows/lint-js.yml
This takes the action from running in about 2.5-3 minutes down to running in around 30s.
> Don't build wp-env when doing npm install in CI as those containers are not needed

- composer.json
- composer.lock
Several users ran into issues where a ValueError was encountered when parsing for the reading grade level using the TextStatistics package. 
I found that the package was not setup to handle this for PHP8. Since that package has not been updated in a long time, and has other open PRs waiting on merge for php8 compat I forked the package repo and have made some updates to it. The changes to the composer file in this PR pulls from the master branch in the fork. https://github.com/equalizedigital/textstatistics/
Changes to the TextStatistics package can also potentially solve issues where certain users are unable to complete pass 2 on the full site scan as well.
Fixes: #570
> Point the TextStatistics package to the forked repo

- admin/class-admin-notices.php
- tests/phpunit/Admin/AdminNoticesTest.php
Updates the discount notice for GAAD.
* Updated the dates
* Updated the message
* Updated the utm_campaign
* Used a new option key to avoid conflicts with anyone who saw the notice last year (also deletes last year's key when setting the new one).
> Update the date of the GAAD discount notice to 2024 year dates

- admin/class-admin-notices.php
The PR fixes the admin notices doc blocks that were improperly titled.
> Fixed improperly titled admin notice doc blocks

- accessibility-checker.php
- admin/class-admin-notices.php
- includes/rules/empty_button.php
- includes/rules/empty_heading_tag.php
- includes/rules/empty_link.php
- includes/rules/iframe_missing_title.php
- includes/rules/img_alt_empty.php
- includes/rules/img_linked_alt_empty.php
- includes/rules/img_linked_alt_missing.php
- includes/rules/long_description_invalid.php
- includes/rules/missing_title.php
- readme.txt
The PR fixes issues within rules where strict data comparisons from the refactor broke functionality.
* Fixed: type Casting on several rules
* Fixed: strict data comparison on several rules
* Updated: empty heading tag rule to consider aria-label
> Hotfix: Rules strict data comparisons 

- .github/workflows/deploy-on-release-to-dot-org.yml
The step ID in the workflow artefact upload stage was referencing a step that did expose output. I updated it to reference the corrected step ID.
> Use a different steps ID for grabbing zip path

- .github/workflows/deploy-on-release-to-dot-org.yml
This artefact was to be uploaded to the release but it doesn't work as intended so it can be a manual step for the moment
> Remove the artefact upload step from the deploy workflow

- src/pageScanner/helpers/helpers.js
Fixes an issue introduced in last merges with the helper to get fontsize
> Check for `typeof` 'number' instead of `instanceof Number`

- includes/rules/iframe_missing_title.php
This PR adds a check for `display:none` and `visibility: hidden` before determining if it should create an issue for an iframe. Google tag manager iframe should no longer create noise with this change since it has both.
Closes: #184
> Don't flag missing iframe title if it's display: none and visibility: hidden

- includes/rules/link_blank.php
The PR simplifies the allowed phases used in the Link Opens New Window or Tab rule check.
Closes #629
> Updated link_blank rule allowed phrases

- src/pageScanner/checks/paragraph-styled-as-header.js
Links that are modified by the New Window Warning plugin contain an `<i>` tag, which highlighted the possible header check was checking the containing tags incorrectly. This PR updates it to check if the tag wraps the entire text instead of simply checking it exists inside the scanned node.
Fixes: #652
> Only consider possible heading if the tag wraps the entire text content

- includes/validate.php
This PR makes a change that excludes the JS rules from the PHP rule check flow when a post is updated. It prevents any JS rule issues from being deleted from the database at the end of the PHP scan (they will still be deleted if corrected when the JS scan runs).
This solves the issue reported that specific ignored issues (investigating, I found that it was all JS rules subject to this bug) would return when posts were updated and no longer be ignored.
Fixes: #655
> Don't operate on JS rules when doing rulecheck for php ruleset

- admin/class-admin-notices.php
This PR adds a filter for the screens, which removes the admin notices. Adding to support a change in the pro plugin when moving full site scan to dedicated page.
> Add a filter for the screens which remove admin notices

- includes/classes/class-rest-api.php
To support tracking fails and handle a performance enhancement for the full site scan properly some addition things need to happen when the js validate method is running.
In an effort to avoid adding any more pro supporting functional code to the free plugin I am adding this filter so that the functional code can stay in the pro plugin entirely.
> Add action in js validate that sends the request through to operate on

- src/pageScanner/checks/paragraph-not-empty.js
This PR changes the empty paragraph check to look at all child nodes rather than just the first.
When the check was added, I assumed the first child node would not be just whitespace. This allowed unexpected failures when the first element was a space.
Fixes: #666
> Check all child nodes inside a paragraph rather than just the first

- admin/class-ajax.php
This PR makes the "view on page" link not ambiguous by adding the issue ID to the `aria-label` which keep the string translatable.
Fixes #217
> Updated view on page aria-label with issue ID

- src/admin/sass/accessibility-checker-admin.scss
This PR adds a max width of 100% to the issue image/svg to prevent it from breaking outside the column.
Fixes #111
> Added max width to issue image/svg

- admin/class-frontend-highlight.php
- includes/classes/class-enqueue-frontend.php
This PR adds a filter (used in 2 places) that will allow a site owner to choose to output the frontend highlighter to people, even those without edit_post permissions on the currently viewed post.
TODO: update the `since` tag in the filter docs if we schedule this to go out in a specific release.
Usage example:
``` PHP
/*
* Returning True allows the current visitor to see the highlighter.
*
* Default value is false. You can use a function instead to perform
* more fine-grained checks as per your needs.
*/
add_filter('edac_filter_frontend_highlighter_visibility', '__return_true');
```
Closes: #669
> Add filter to allow frontend highlighter to be shown to other users

- admin/class-ajax.php
- includes/helper-functions.php
- src/admin/sass/accessibility-checker-admin.scss
This PR updates the summary tiles to an unordered list with aria labels for improved a11y.
- Added helper class to output summary items as list items with aria labels.
- Update summary labels to be translatable.
- Update CSS logic
- Linked asterisk to description and added screen reader text
Fixes #359
Fixes #358
> Summary panel a11y

- admin/class-ajax.php
- src/admin/sass/accessibility-checker-admin.scss
This PR removes a wrapper div, making summary items be `<li>` elements only so they are read out correctly to a screen reader.
The styles were tweaked to use CSS grid for styling. There are some minor differences after the style changes.
> Wrap the summary items inside only a ul and li items (removing a div)

- accessibility-checker.php
- admin/class-ajax.php
- changelog.txt
- package.json
- readme.txt
- src/admin/sass/accessibility-checker-admin.scss
Steve Jones (4):
William Patton (7):
> Release v1.14.0

- accessibility-checker.php
- package.json
- partials/settings-page.php
- readme.txt
- src/admin/sass/accessibility-checker-admin.scss
Adds an extra class to settings page wrapper for when pro callout will appear that can extend the container, preventing cramped settings fields in new styles.
> Add a class on the settings page container when pro callout will show

- src/frontendHighlighterApp/sass/app.scss
This PR tweaks some mobile style rules to prevent the toggle button from floating right in the highlighter widget when it's set to display on the left.
It also reorders some of the CSS so it's easier to read and follow by avoiding breaking the same class name up into two sections of rules.
> Prevent frontend highlight toggle button floating right on mobile if it's set to show on the left

- includes/rules/empty_link.php
- tests/phpunit/includes/rules/EmptyLinkTest.php
This PR makes is so that empty links are flagged appropriately by:
* Correcting some variables that were being checked
* Flagging an error if it's empty plain text and there is no `img`, `input` or `i` tags for further checks
Tests were also added to confirm the behaviour of the rule matches the intention against some test data.
Fixes: #697
> Fixed: Allow empty_link rule to detect actually empty links

- includes/rules/missing_form_label.php
This PR adds a check inside of the missing_form_label that will prevent an error being flagged for an input with type of 'image' if it has non-empty alt text. A screen reader will use the alt text even when there is no label.
Fixes: #610
> Enahcement: Image inputs with alt text shouldn't flag for missing_form_label

- includes/classes/class-edac-dom.php
- includes/helper-functions.php
- includes/rules/video_present.php
This PR adjusts how file extensions are checked in some rules so that `avif` does not get checked by them since it is not a video.
The reason this was happening was due to the way file extensions were being checked. They were matching `avi` in `avif`. I have created a helper that checks the extension matches the full extension and not just part of it.
Fixes: #598
> Fix: Don't flag .avif as missing trascript or video present

- includes/validate.php
This PR calls the method to delete issues when a post is trashed during the validate method at the point it would early bail since post is trashed.
I moved the trash bail later in the method to ensure that any other quicker bail checks can run before it runs database queries for deleting issues.
This is needed here because Gutenberg editor does not fire the `wp_trash_post` hook because it uses rest API which updates a post with trash status where as classic editor and the quick actions in post lists invoke the actual trash functions. Deleting via rest does have a different action we could bind to - `rest_delete_{$post_type}` but using it is less clean than the way `wp_trash_post` works so I decided to use the method in this PR to solve this instead.
> Purge the post data if the saved post is in or is moving to trash

- composer.json
- composer.lock
- package.json
- phpstan.neon
This PR adds PHPStan to the project set with run level of 2 which finds 95 errors at the current time.
There is no action added to run this check in CI currently, we should fix the issues locally in a followup PR (or multiple followup PRs) before adding a CI action for catching things.
> Add PHPStan to the project

- admin/class-helpers.php
- admin/class-issues-query.php
- includes/helper-functions.php
This PR inlines variables at the return statement if they existed only to be returned. None of these seemed to aid in readability in my view so I swapped every instance that was detected.
There were 2 other instances inside the `simple_html_dom.php` file that I did not modify here since that package is a cloned 3rd party file.
> Inline some single use variables at function returns

- composer.json
- includes/classes/WPCLI/BootstrapCLI.php
- includes/classes/WPCLI/Command/CLICommandInterface.php
- includes/classes/WPCLI/Command/DeleteStats.php
- includes/classes/WPCLI/Command/GetSiteStats.php
- includes/classes/WPCLI/Command/GetStats.php
- includes/classes/class-plugin.php
- phpcs.xml
- tests/phpunit/Mocks/Mock_WP_CLI.php
- tests/phpunit/TestHelpers/DatabaseHelpers.php
- tests/phpunit/TestHelpers/Mocks/Mock_WP_CLI.php
- tests/phpunit/includes/classes/WPCLI/BootstrapCLITest.php
- tests/phpunit/includes/classes/WPCLI/Commands/DeleteStatsTest.php
- tests/phpunit/includes/classes/WPCLI/Commands/GetSiteStatsTest.php
- tests/phpunit/includes/classes/WPCLI/Commands/GetStatsTest.php
This adds a setup to handle WP-Cli commands and adds a pair of commands to start with. It scopes them under a `accessibility-checker` command scope.
- delete-stats request a post ID passed as the first positional argument
- Delete stats for post with ID 123: `wp accessibility-checker delete-stats 123`
- `get-stats` accepts a post ID passed as first positional argument
- Get stats for post with ID 123: `wp accessibility-checker get-stats 123`
- `get-site-stats` accepts no paramiters
- Get the stats for all the scanned pages on the site: `wp accessibility-checker get-site-stats` 
Closes: #674
> Add wp cli commands to get stats and delete stats

- .github/PULL_REQUEST_TEMPLATE.md
Adds a simple PR template with some checkboxes to remind about tagging PRs with the associated issue and about adding tests.
> Add a basic PR template 

- admin/class-admin.php
This PR avoids making the Meta_Boxes class injected into the Admin class implicitly nullable. Since it can never be null, the default null value is removed instead of making the type hint nullable.
Fixes: #706
> PHP 8.4 deprecation notice fix for implicitly nullable Meta_Boxes

- src/admin/sass/accessibility-checker-admin.scss
This PR fixes the EDAC widget icon background size.
Before:
After:
> Fixed: background size style placement

- admin/class-enqueue-admin.php
- tests/phpunit/Admin/EnqueueAdminTest.php
This PR adds an extra `$pagenow` value to check of `post-new.php` when determining if the editor script should be added.
Gutenberg new post page us `post-new.php` but when editing a post it is `post.php`. The latter of which would load the script while the former would not.
Fixes: #716
> Fix: When creating new post in Gutenberg the JS checks were not run till page reload

- src/frontendHighlighterApp/index.js
This PR improves the accessibility of the highlight buttons.
- Added unique aria-label
- Added `aria-haspopup="dialog"`
- Switch to the `setAttribute` method to ensure attributes are added correctly
- Cleaned up commented code
Fixes #218 
Card: https://3.basecamp.com/3579237/buckets/29333825/card_tables/cards/7667317750
> updated: highlight button aria-label to be unique and added aria-haspopup equal to dialog

- includes/classes/class-enqueue-frontend.php
- src/frontendHighlighterApp/index.js
- webpack.config.js
This PR adds `aria-label="Disable Page Styles"` to the disable styles button to provide more context to screen readers. It adds the ability to translate strings in the JavaScript file.
Fixes: #362
> added: aria label to the disable styles button

- accessibility-checker.php
- admin/AdminPage/FixesPage.php
- admin/AdminPage/PageInterface.php
- admin/class-admin-notices.php
- admin/class-enqueue-admin.php
- composer.json
- includes/classes/Fixes/FixInterface.php
- includes/classes/Fixes/FixesManager.php
- includes/classes/class-plugin.php
- includes/options-page.php
- partials/admin-page/fixes-page.php
This PR introduces a framework to manage various fixes that the plugin can apply to users sites. There are no actual fixes added yet in this PR as it just puts the framework in place for adding the fixes.
- A settings page is added, initially supporting just checkbox type options
- Filters exist to add sections to the options page and register settings to any section on it
- Actions (will be) added where the fixes will have to be run or triggered.
> Add framework to handle various different fixes that the plugin can apply

- admin/AdminPage/FixesPage.php
- admin/AdminPage/FixesSettingType/Checkbox.php
- admin/AdminPage/FixesSettingType/Text.php
- includes/classes/Fixes/Fix/SkipLinkFix.php
- includes/classes/Fixes/FixesManager.php
- partials/admin-page/fixes-page.php
- src/admin/fixes-page/conditional-disable-settings.js
- src/admin/index.js
- src/admin/sass/accessibility-checker-admin.scss
- src/frontendFixes/Fixes/skipLinkFix.js
- src/frontendFixes/index.js
- tests/phpunit/helper-functions/GetFileOpenedAsBinaryTest.php
- tests/phpunit/helper-functions/UrlExistsTest.php
- webpack.config.js
This PR adds a _fix_ to the plugin that users can add a skip link to their pages with.
* It provides a checkbox to enable the feature and a text input to type in the target ID
* The target ID field access a comma separated list of possible IDs to target. The list can include the `#` or not and it will be handled appropriately.
* When enabled it inlines some JS that will attempt to detect if there is a valid skip link already and if so do nothing
* If no skip link is found it will attempt to find one of the IDs referenced in the targets list.
* If it finds an ID then it will clone a skip link and some styles for it from a `<template>` tag added to the page.
If you are using a FSE enabled theme like Twenty Twenty-Four then it has some features to add a skip links that lives outside the …
> Added: Fix for adding skip links when they are not there

- includes/classes/Fixes/Fix/HTMLLangAndDirFix.php
- includes/classes/Fixes/Fix/SkipLinkFix.php
- includes/classes/Fixes/FixInterface.php
- includes/classes/Fixes/FixesManager.php
- src/frontendFixes/Fixes/langAndDirFix.js
- src/frontendFixes/index.js
This PR adds a _fix_ that users can toggle on to include the `lang` and `dir` attributes on the root `html` element.
The fix uses a filter on `language_attribute` to add them but includes an additional JS fallback for themes which do not have the `language_attributes()` function in the correct place.
Note: This is based from the skip-link fix which is why the diff currently looks so large. It does also include some changes to how the fixes manager registers and invokes fixes - namely the inclusion of a `run` method requirement inside of fixes to separate settings and registration code from actual runner code.
> Fix: add lang and dir attributes to html element

- includes/classes/Fixes/Fix/CommentSearchLabelFix.php
- includes/classes/Fixes/FixesManager.php
This PR adds an accessibility fix for adding missing comments and search form labels.
Card: https://3.basecamp.com/3579237/buckets/29333825/card_tables/cards/7652429114
> added: comment and search form labels fix

- includes/classes/Fixes/Fix/TabindexFix.php
- includes/classes/Fixes/FixesManager.php
- src/frontendFixes/Fixes/tabindexFix.js
- src/frontendFixes/index.js
This PR adds a fix for removing the `tabindex` attribute.
```html
<input type="text" tabindex="5" placeholder="Input with unnecessary tabindex">
<a href="#" tabindex="3">Focusable link with href</a>
<select tabindex="4">
<option>Option 1</option>
<option>Option 2</option>
</select>
<textarea tabindex="2" placeholder="Textarea with unnecessary tabindex"></textarea>
<button tabindex="1">Button with unnecessary tabindex</button>
```
```html
<div role="button" onclick="alert('Clicked!')">Div styled as a button without tabindex</div>
<a role="button" onclick="alert('Clicked!')">Anchor styled as a button without href or tabindex</a>
```
```html
<a role="button" tabindex="5">Anchor styled as a button with tabindex (no href)</a>
<div role="button" tabindex="0" onclick="alert('Clicked!')">Div …
```
> Added: remove tab index fix

- includes/rules/img_alt_redundant.php
The PR adds an additional check for `figcaption` to the Duplicate Alternative Text check.
Fixes #732
> Added: additional check for figcaption to the Duplicate Alternative Text check

- includes/classes/Fixes/Fix/SkipLinkFix.php
Updates some labels for skip link options to make them more clear what they are for and less duplicative.
> Make some skip link option labels less ambiguous

- includes/classes/Fixes/Fix/PreventLinksOpeningNewWindowFix.php
- includes/classes/Fixes/FixesManager.php
- src/frontendFixes/Fixes/preventLinksOpeningNewWindowFix.js
- src/frontendFixes/index.js
Adds a fix that can be used to remove all target="_blank" values from links on a page.
This fix runs before ANWW runs so it removes the new window opening links before it detects and operates on them.
> added: Fix that can remove target="_blank" from links

- includes/classes/Fixes/Fix/LinkUnderline.php
- includes/classes/Fixes/FixesManager.php
- package-lock.json
- src/frontendFixes/Fixes/underlineFix.js
- src/frontendFixes/index.js
This PR adds the Force Underline on links Fix.
1. Excludes links inside of `nav` elements
2. Add filter `edac_filter_frontend_fixes_data` to allow for changing the target elements. The default is `a`.
Card: https://3.basecamp.com/3579237/buckets/29333825/card_tables/cards/7652429605
> added: force underline fix

- includes/classes/Fixes/Fix/ReadMoreAddTitleFix.php
- includes/classes/Fixes/FixesManager.php
- src/admin/sass/accessibility-checker-admin.scss
This adds it to the normal read more, the excerpt and the excerpt more.
Note: This does not work with the query loop block as they explicitly override anything from the filter if someone has filled in the read more text element in the block settings. See: https://github.com/WordPress/gutenberg/blob/abf72c95b1da1b8f6709858bb750e1d56782c27d/packages/block-library/src/post-excerpt/index.php#L39C5-L47C5
> Add a fix class for adding post title to read more links

- includes/classes/Fixes/Fix/AddFileSizeAndTypeToLinkedFilesFix.php
- includes/classes/Fixes/FixesManager.php
Adds a fix class that will add the file size and the type to the link text for files.
> Add Fix class to add file size and extension to file links

- src/frontendFixes/Fixes/underlineFix.js
The PR fixes the issue with the underline being applied to navigation links on mouse out. It improves the logic by adding an early return if the element is inside a `nav` or has a `role` of navigation.
> added: an early return for nav menus

- admin/AdminPage/FixesPage.php
- uninstall.php
This PR stores options keys so they can be later deleted if the plugin gets uninstalled
> Delete fix option keys on uninstall

- admin/AdminPage/FixesPage.php
- admin/AdminPage/FixesSettingType/Checkbox.php
- admin/class-enqueue-admin.php
- includes/classes/Fixes/Fix/AddFileSizeAndTypeToLinkedFilesFix.php
- includes/classes/Fixes/Fix/AddLabelToUnlabelledFormFieldsFix.php
- includes/classes/Fixes/Fix/AddMissingOrEmptyPageTitleFix.php
- includes/classes/Fixes/Fix/BlockPDFUploadsFix.php
- includes/classes/Fixes/FixesManager.php
- includes/helper-functions.php
- src/admin/fixes-page/pro-callout.js
- src/admin/index.js
- src/admin/sass/accessibility-checker-admin.scss
- src/frontendFixes/Fixes/tabindexFix.js
This PR brings the settings for the pro fixes into the free plugin and flags them as upgrade features for users. The `run` method is empty for pro fixes and the type is set to `none`.
It also adds a helper to generate pro links and some JS to put a pro flag on settings on the fixes page.
> Include settings for pro fix callouts

- includes/classes/Fixes/Fix/PreventLinksOpeningNewWindowFix.php
- src/frontendFixes/Fixes/preventLinksOpeningNewWindowFix.js
- src/frontendFixes/index.js
Updates the fix that blocks links opening new tabs/windows.
* Updates the description and title.
* Adds a modifier class detection for `.edac-allow-new-tab` that will prevent the target="_blank" being removed if it's on the link or on a parent of the link.
> Prevent links opening new tabs tweaks

- admin/AdminPage/FixesPage.php
- admin/AdminPage/FixesSettingType/Checkbox.php
- admin/AdminPage/FixesSettingType/Text.php
- admin/class-enqueue-admin.php
- includes/classes/Fixes/Fix/AddFileSizeAndTypeToLinkedFilesFix.php
- includes/classes/Fixes/Fix/AddLabelToUnlabelledFormFieldsFix.php
- includes/classes/Fixes/Fix/AddMissingOrEmptyPageTitleFix.php
- includes/classes/Fixes/Fix/BlockPDFUploadsFix.php
- includes/classes/Fixes/Fix/FocusOutlineFix.php
- includes/classes/Fixes/Fix/HTMLLangAndDirFix.php
- includes/classes/Fixes/Fix/LinkUnderline.php
- includes/classes/Fixes/Fix/MetaViewportScalableFix.php
- includes/classes/Fixes/Fix/PreventLinksOpeningNewWindowFix.php
- includes/classes/Fixes/Fix/RemoveTitleIfPrefferedAccessibleNameFix.php
- includes/classes/Fixes/Fix/TabindexFix.php
- includes/helper-functions.php
- src/admin/sass/accessibility-checker-admin.scss
This PR introduces a way to set help link ids on fixes and a generator to create links with query vars for data.
> Add help link feature for fix descriptions

- admin/AdminPage/FixesPage.php
- partials/admin-page/fixes-page.php
- partials/settings-page.php
This PR removes the Accessibility Fixes link from the plugin menu and moves it to a tab on the settings page.
- removed the menu link
- added tab via existing filters
- updated `aria-label` on tabs nav element
Fixes: https://3.basecamp.com/3579237/buckets/29333825/card_tables/cards/7810260579
> Move fix setting to the settings page in a tab

- scripts/dist.sh
This saves close to 1Mb in size when extracted
> Remove the text statistics test dir from a dist build

- src/frontendFixes/Fixes/removeTitleIfPrefferedAccessibleNameFix.js
Reworks some of the checking logic when processing elements with title tags to favour their preferred accessible names.
> Rework some checks for removing title attribute in favour of a preferred accessible name

- .github/workflows/code-coverage-and-coveralls.yml
One of the steps in the code coverage workflow is no longer working and triggering a stop for the workflow that handles code coverage. This PR bumps that step action to the latest version.
See a failure here: https://github.com/equalizedigital/accessibility-checker/actions/runs/11277744379/job/31364613280
> Bump upload-artefact in action to v4

- src/pageScanner/index.js
With some additional rules moved over the the JS scan some items inside the query monitor container were being flagged (new link warnings). 
This PR excludes the container from the scan by using the `context.exclude[]` object passed to the runner.
Excluded by id #query-monitor-main
> Exclude the query monitor container from the JS scan.

- src/frontendHighlighterApp/fixesModal.js
The code that was running during modal trigger was not excluding the modal from the parts that were handling the aria-hidden attributes of elements. This PR should fix that.
Basecamp card: https://3.basecamp.com/3579237/buckets/29333825/card_tables/cards/7923127676
> Prevent modal from having aria hidden incorrectly added

- includes/rules.php
Removes the fixes setting from the broken_skip_link_anchor rule. These fixes are not entirely connected to this rule check.
Basecamp task: https://3.basecamp.com/3579237/buckets/29333825/card_tables/cards/7922669151
> Don't show skip link fixes on broken_skip_link_anchor rule

- src/frontendHighlighterApp/index.js
- src/frontendHighlighterApp/sass/app.scss
Shifts the fix button in the inline highlighter to be inline with the other buttons in the panel.
Basecamp card: https://3.basecamp.com/3579237/buckets/29333825/card_tables/cards/7922908949
> Iinline frontend highlighter fix button

- admin/class-enqueue-admin.php
- includes/classes/class-rest-api.php
- partials/custom-meta-box.php
- src/admin/index.js
- src/admin/sass/accessibility-checker-admin.scss
- src/editorApp/checkPage.js
- src/editorApp/index.js
EDIT: this PR was repurposed to be just a 'Clear Issues' button instead of a rescan button.
~~This PR adds a rescan button in the edac widget area that will allow a user to trigger a rescan of the post's content.~~
Adds a clear issues button to the editor.
It also resolves an event-building issue resulting in duplicated iframes and ajax/rest calls happening when posts were being opened for editing/resaved.
https://github.com/user-attachments/assets/974a1745-1e0d-4039-bc36-5036448ae83a
Basecamp card: https://3.basecamp.com/3579237/buckets/29333825/card_tables/cards/7922855194
> Add a Clear Issues button in the editor

- includes/classes/Fixes/Fix/SkipLinkFix.php
This splits the skip links fix up so that each link get's it's own container.
https://github.com/user-attachments/assets/88040c10-afc4-488b-af17-a4e9060b3e60
Basecamp card: https://3.basecamp.com/3579237/buckets/29333825/card_tables/cards/7652418924
> Make skip links have their own individual containers

- admin/class-ajax.php
- includes/classes/Fixes/FixesManager.php
- includes/classes/class-enqueue-frontend.php
- src/frontendHighlighterApp/index.js
This PR adds a permission check on the rest endpoints and capability checks (through `edac_filter_settings_capability`) around some points that would generate fix links and data to prevent showing them to users that can't toggle them
> Handle permissions and display for fixes

- src/common/sass/_fix-settings.scss
- src/frontendHighlighterApp/sass/app.scss
When testing the fixes release with TwentyTwenty, theme style leaking into the modal was noticed. This caused style and layout shifting when styles were disabled and enabled. The theme styles should be overridden in the modal and highlight panel.
This PR adds more style rule overrides to combat the style leaking.
<details>
<summary>Video of the styles being toggled on and off after this change showing no visual differences (except scrollbar changes caused by the underlying content)</summary>
https://github.com/user-attachments/assets/945f1046-cfdb-42be-9f95-530b394cf683
</details>
Basecamp card: https://3.basecamp.com/3579237/buckets/29333825/card_tables/cards/7923057011
> Style more elements to try prevent leaking from theme into modal

- src/admin/summary/summary-tab-input-event-handlers.js
Adds some retry logic and a return that will prevent errors being thrown if the thickbox target element is not yet available or has not yet been restored when the fix button is clicked.
https://3.basecamp.com/3579237/buckets/29333825/card_tables/cards/7956375078
> Handle timing issue for fix button that triggers thickbox

- src/frontendFixes/Fixes/tabindexFix.js
This looks at every element, sets positive tabindex to `0`, leaves `-1` and adds `0` to elements with roles that are changed to buttons.
> Rework tabindex fix to handle all elements with tabindex

- admin/class-ajax.php
- admin/class-frontend-highlight.php
- includes/classes/Fixes/Fix/AddFileSizeAndTypeToLinkedFilesFix.php
- includes/classes/Fixes/Fix/AddLabelToUnlabelledFormFieldsFix.php
- includes/classes/Fixes/Fix/AddMissingOrEmptyPageTitleFix.php
- includes/classes/Fixes/Fix/CommentSearchLabelFix.php
- includes/classes/Fixes/Fix/HTMLLangAndDirFix.php
- includes/classes/Fixes/Fix/LinkUnderline.php
- includes/classes/Fixes/Fix/ReadMoreAddTitleFix.php
- includes/classes/Fixes/Fix/RemoveTitleIfPrefferedAccessibleNameFix.php
- src/common/sass/_fix-settings.scss
- src/common/saveFixSettingsRest.js
- src/frontendFixes/Fixes/tabindexFix.js
- src/frontendHighlighterApp/fixesModal.js
- src/frontendHighlighterApp/index.js
- src/frontendHighlighterApp/sass/app.scss
This PR includes various tweaks and fixes to get ready for next release.
* Add some additional styles to frontend fixes modal to prevent more leaking from theme.
* Update the save success message to be clear about what visiting editor does.
* Set a width for modal to reduce layout shift.
* Add better label to fix issue button for frontend modal and add aria-haspopup
* Set even fake buttons and links to `0` tabindex when operating on them
* Add a help id to label fix
* Add fieldset and legend to modals
* Add an opening message to fix modals
* Update the nice names of several fixes
> Tweaks and changes to prepair for next release (1.16.0)

- includes/classes/Fixes/Fix/AddFileSizeAndTypeToLinkedFilesFix.php
- includes/classes/Fixes/Fix/AddLabelToUnlabelledFormFieldsFix.php
- includes/classes/Fixes/Fix/AddMissingOrEmptyPageTitleFix.php
- includes/classes/Fixes/Fix/BlockPDFUploadsFix.php
- includes/classes/Fixes/Fix/CommentSearchLabelFix.php
- includes/classes/Fixes/Fix/FocusOutlineFix.php
- includes/classes/Fixes/Fix/HTMLLangAndDirFix.php
- includes/classes/Fixes/Fix/LinkUnderline.php
- includes/classes/Fixes/Fix/MetaViewportScalableFix.php
- includes/classes/Fixes/Fix/ReadMoreAddTitleFix.php
- includes/classes/Fixes/Fix/RemoveTitleIfPrefferedAccessibleNameFix.php
- includes/classes/Fixes/Fix/TabindexFix.php
This PR updated fix setting descriptions to not be plural.
Fixes: https://3.basecamp.com/3579237/buckets/29333825/card_tables/cards/7968004100
> updated: fixes setting description to not be plural

- includes/classes/Fixes/Fix/CommentSearchLabelFix.php
This PR adds help ids to some fields that were missing them
> Add help ID to fields for comment and search form labels fix

- src/admin/summary/summary-tab-input-event-handlers.js
This PR tackles the last remaining part of the card this is from. It ensures the thickbox title has the new 'fancy name' rather than 'Fix Settings' or pulling a redundant header from the contents.
Basecamp card: https://3.basecamp.com/3579237/buckets/29333825/card_tables/cards/7968806839
> Output fancy name as the thickbox modal title

- includes/classes/Fixes/Fix/AddLabelToUnlabelledFormFieldsFix.php
This PR fixes an issue where a nicename for one fix was incorrectly set to a different fixes name.
We can point this to the main branch to do a hotfix on Monday but it is probably best to do a normal release and get other small things out alongside it.
> Restore the correct nicename for the label form fields fix

- admin/site-health/class-free.php
- admin/site-health/class-pro.php
- includes/classes/Fixes/FixesManager.php
- tests/phpunit/includes/classes/Fixes/FixesManagerTest.php
Adds fixes and their values as a json_encoded string to the site health page for both the free and the pro sections.
> Add fixes settings to site health

- src/admin/summary/summary-tab-input-event-handlers.js
- src/common/saveFixSettingsRest.js
In some situations, we would want to programmatically set an editor link. This PR sets up the required handling in the script. 
Part of a resolution to allow better fix settings save messaging on the open issues page.
> Handle editorLink passed via edac_script_vars

- admin/class-admin-notices.php
- partials/admin-page/fixes-page.php
When fixes settings are saved, a transient is set to be used as a flag for notifications. It is used in the fixes_page.php partial to output a notice about rescanning and flushing the cache.
It's done this way rather than via admin_notifications because we are unhooking all other notifications when on the settings pages.
> Show a notice when fixes settings are saved on options page

- includes/rules/missing_table_header.php
This pull request includes updates to the `includes/rules/missing_table_header.php` file to improve the accessibility checks for table headers. The most significant changes involve renaming a function for clarity, modifying the logic to check for proper table headers, and ensuring that the function returns an appropriate value when no tables are found.
Key changes:
-  Renamed the function `edac_th_match_td` to `edac_has_proper_headers` for better clarity.
-  Enhanced the logic within the `edac_has_proper_headers` function to check for valid table headers by verifying the presence of header text and valid scope attributes.
-  Modified the `edac_rule_missing_table_header` function to return an empty errors array if no tables are found, ensuring consistency in the return type.
-  Corrected a …
> Fix: Improve table header detection logic to correctly validate row headers

- includes/classes/class-summary-generator.php
When this is here, it always results in a falsey value which loosely casts to 0, making this only able to retrieve warning counts of siteid 0.
It was added in https://github.com/equalizedigital/accessibility-checker/commit/6732c3d8d297e4e2868f9c579b08a3c6ad4d0134#diff-350d3eed90dcfd8d1466cc7e406d1b17b604e284b62d478a7eb271cdd11287e7R765 so it's been here 3-4 years.
> Remove a duplicated siteid reference in query

- admin/class-ajax.php
This pull request includes an update to the `admin/class-ajax.php` file to add a new conditional check for displaying the ignore button based on user permissions.
Changes to conditional display logic:
* [`admin/class-ajax.php`](diffhunk://#diff-87159e3bf5e81593c7698827c5dc895f087a1766d135de0dd7588b340903404eR498-R500): Added a conditional check to display the ignore button only if the `$ignore_permission` variable is set to `true`.
> added: ignore permission logic to ignore button

- admin/class-welcome-page.php
Swap the array key that is checked for the passing urls to `posts_without_issues` since `posts_without_issues_formatted` doesn't exist in the summary array.
The key was changed to one that will always be empty in this commit: https://github.com/equalizedigital/accessibility-checker/commit/1c47aa73d0659dc514b768974a27af44eac07c2d
> Fix: URLs with 100% score will always be 0

- src/frontendHighlighterApp/index.js
This PR adds a simple retry later to init the Frontend Highlighter. This should solve the issue where Cloudflare Rocket Loader defer prevents the highlighter from initialising.
It will try init first on `DOMContentLoaded` and then later at `load`. It adds a variable as a flag to track if the init code has already run to prevent it duplicating on `load` if it already ran when initially intended.
> Enhancement: Retry frontend highlighter init later

- .github/workflows/phpunit.yml
- admin/class-scans-stats.php
- tests/phpunit/helper-functions/OrdinalTest.php
This pull request includes an update to the `summary` method in the `admin/class-scans-stats.php` file to add a new parameter for skipping the cache.
This is needed for the multisite support where stats are retrieved through the plugin.
There are unrelated workflow and test changes in this PR that are not related to the cache skip change. The `latest` version of some docker images has changed and some adjustments were needed to CI workflows.
> Add a flag to skip cache when getting scan stats

- admin/AdminPage/FixesPage.php
- admin/class-admin-notices.php
This pull request removes the functionality related to the removal of admin notices in the `admin` module. The most important changes include the removal of the `add_slug_to_admin_notices` method and the `edac_remove_admin_notices` method, along with their associated hooks.
Removal of admin notices functionality:
* [`admin/AdminPage/FixesPage.php`](diffhunk://#diff-c9f2ca5909e6e4c48b97530f86fd6dadcb2475aaf67ba9d1750546dcf0604417L56): Removed the `add_slug_to_admin_notices` method and the associated filter `edac_filter_remove_admin_notices_screens` from the `add_page` method. [[1]](diffhunk://#diff-c9f2ca5909e6e4c48b97530f86fd6dadcb2475aaf67ba9d1750546dcf0604417L56) [[2]](diffhunk://#diff-c9f2ca5909e6e4c48b97530f86fd6dadcb2475aaf67ba9d1750546dcf0604417L102-L112)
* …
> removed: unused admin notices functionality from FixesPage and Admin Notices classes

- includes/classes/class-rest-api.php
This now allows posts that no longer exist to be flushed out of the table of issues when passed a specific 'skip_post_exists_check' parameter.
Why: A support request came in about issues existing for a post that was deleted. It is difficult to clear these issues out without database access and the clear-issues endpoint had a check to validate that the post exists in it and that the post type was valid.
> Make the endpoint for clearing issues less strict

- .github/workflows/deploy-on-release-to-dot-org.yml
Fixes SVN not being available in `ubuntu-latest` and installs it in the deploy container
> Install SVN in deploy container if not already there

- admin/AdminPage/FixesPage.php
- admin/class-admin-notices.php
- admin/class-ajax.php
- admin/class-frontend-highlight.php
- admin/site-health/class-free.php
- admin/site-health/class-pro.php
- src/emailOptIn/index.js
- src/frontendHighlighterApp/index.js
This pull request includes updates to improve localization throughout the codebase by replacing hardcoded strings with translatable strings using the `__()` function. These changes ensure that all user-facing text can be translated into different languages, enhancing accessibility for non-English speakers.
* Updated the `add_fixes_tab` method in `admin/AdminPage/FixesPage.php` to make the "Fixes" label translatable.
* Replaced hardcoded error messages with translatable strings in multiple methods (`welcome_page_post_count_change_notice_ajax`, `edac_black_friday_notice_ajax`, `edac_gaad_notice_ajax`, `edac_review_notice_ajax`, `edac_password_protected_notice_ajax`) within `admin/class-admin-notices.php`. Examples include "Permission Denied" and "Update option wasn't successful." …
> Update translation functions for better localization
