includes/validate.php

When used in specific environments, the file_get_html() function fails because it cannot verify the SSL certificate. 
This adds a filter that allows the SSL certificate verification to be bypassed.
I did consider including an option to allow this, but because of potential security risk, it seems more prudent to make this a developer-level change.
To use add the filter `add_filter( 'edac_no_verify_ssl', '__return_true' );`. This will include an extra context arg.
This code change accounts for the pro activation authorization functionality but allows local or staging environments where the SSL certificate authentication may fail to enable plugin usage.
Fixes https://github.com/equalizedigital/accessibility-checker/issues/81

add context stream filter to allow disabling ssl verify

---

includes/validate.php

This PR:
1) Adds a sanity check to make sure the page that should be validated matches the base url of the site (this should always be the case.) [[Ref]](https://github.com/equalizedigital/accessibility-checker/blob/dbde4d879dc3cfd247a918f5e944459a516f34e6/includes/validate.php#L234-L235)
2) Adds an [http context option](https://www.php.net/manual/en/context.http.php) `follow_location`, that when set to false will prevent validating a page that [header redirects](https://developer.mozilla.org/en-US/docs/Web/HTTP/Redirections) to another location. [[Ref]](https://github.com/equalizedigital/accessibility-checker/blob/dbde4d879dc3cfd247a918f5e944459a516f34e6/includes/validate.php#L195-L202) [[Ref]](https://github.com/equalizedigital/accessibility-checker/blob/dbde4d879dc3cfd247a918f5e944459a5 …

Block site scans from following redirects off-site.

---

README.txt

209 release an update that changes out the demo video on our public plugin listing

---

accessibility-checker.php

Replicated the issue using:
$issue_density_array = get_post_meta( 5000, '_edac_density_data' );
confirmed that after this fix the warning is no longer shown.

Fixes #245

---

src/app/sass/accessibility-checker.scss
src/globals/sass/_variables.scss

244 fix frontend highlighting mobile responsive

---

includes/helper-functions.php
includes/validate.php

Fixes #242
Fixes #243
Fixes spacing

Exclude WP admin bar and Query Monitor from scans

---

src/app/index.js
src/app/sass/accessibility-checker.scss

Fixes #271, #272, #273:
56e280cddbd873a5332e91007cd3f28a5616a0bb

hotfix: Frontend highlighter ui issues

---

README.txt
accessibility-checker.php
src/admin/index.js

Closed old PR based on develop. Opened as new PR based on master.
This fixes a timing issue with the ajax calls [ref](https://github.com/equalizedigital/accessibility-checker/issues/275#issuecomment-1716118687)

Fixes #275

---

accessibility-checker.php
includes/classes/class-helpers.php

Fixes #254

---

includes/rules/img_alt_invalid.php

- Adds rules.
- Updates localization domain.
- Replaces `goto` logic.

Fixes #228

---

src/app/index.js

Fixes #265, Fixes: #285

---

accessibility-checker.php
includes/classes/Rest_Api.php
includes/classes/class-rest-api.php
includes/classes/class-scans-stats.php
includes/classes/class-widgets.php
includes/enqueue-scripts.php
partials/welcome-page.php
src/admin/index.js
src/admin/sass/accessibility-checker-admin.scss

- Adds limit to scan stat queries
- Adds Ajax based data request to widget
- Improves caching

264 reports dashboard widget and welcome screen refactor

---

composer.json
composer.lock
src/admin/index.js

New PR based on dev:
- Updates js
- Adds davechild/textstatistics to composer.json

Fixes #297

---

includes/classes/class-settings.php
includes/classes/class-welcome-page.php
includes/purge.php

- updates purge process to use more performant code
- updates logic that Settings->get_scannable_post_types uses
- removes unneeded "%" character from class-welcome-page

Fixes #317

---

includes/classes/class-helpers.php
includes/classes/class-issues-query.php
includes/classes/class-rest-api.php
includes/classes/class-scans-stats.php
includes/classes/class-settings.php

@SteveJonesDev - I couldn't replicate the problem, but do see that if $tests_count is 0 it will error. This should fix.

Fixes #315

---

includes/classes/class-helpers.php
includes/classes/class-scans-stats.php
includes/classes/class-welcome-page.php
src/admin/index.js

If approved this PR:
- Adds localized formatting helpers 
- Adds formatted results to the scan_stats summary
- Used the formatted results on the dashboard widget
- Updates date on dashboard to use server localization rather than browser
- Uses the formatted results on the welcome page

312 welcome page and dashboard widget number format

---

includes/enqueue-scripts.php
src/app/index.js

I kept trying to make this hard...
(Autoptimize plugin)
**Before w/styles disabled**
**After w/styles disabled**

Fixes #216

---

includes/classes/class-scans-stats.php

- Update passed_percentage calculation

321 passed tests should not be able to be negative

---

includes/classes/class-scans-stats.php

If approved this PR:
- fixes avg_issue_density_percentage not accounting for siteid or ignores

Fixes #323

---

includes/classes/class-helpers.php

- Add support for formatting numbers and percentages in php installs that were build without the intl library

Fixes #331

---

.gitignore
.wp-env.json
composer.json
hard-reset.sh
install.sh
package.json
patches/@wordpress+env+8.8.0.patch

- Add the accessibility checker wp env package as a dependency

Add accessibility checker wp env package

---

includes/rules/link_ms_office_file.php

updated - logic for the link to MS Office file #336

---

includes/classes/class-helpers.php
includes/classes/class-scans-stats.php
includes/classes/class-welcome-page.php
includes/classes/class-widgets.php

Fixes issue from pro repo: https://github.com/equalizedigital/accessibility-checker-pro/issues/121

updated - last full-site scan label and date format

---

includes/system-info.php

- Update system-info.php to stop showing edac_authorization_username & edac_authorization_username
- Update system-info.php to show edacp_authorization_username & edacp_authorization_username for pro users

Fixes #349

---

README.txt
accessibility-checker.php
includes/classes/class-helpers.php
includes/validate.php

- Adds check if server file_get_contents calls to the site domain are to a loopback ip.
- Adds logic to not validate ssl on loopback calls.

Hotfix to handle loopback environments

---

accessibility-checker.php

updated - description #380

---

accessibility-checker.php
includes/classes/class-admin-notices.php
includes/classes/class-helpers.php
includes/classes/class-rest-api.php
includes/classes/class-scans-stats.php
includes/classes/class-settings.php
includes/enqueue-scripts.php
includes/helper-functions.php
includes/options-page.php
includes/rules/color_contrast_failure.php
includes/rules/incorrect_heading_order.php
includes/rules/missing_form_label.php
includes/rules/missing_title.php
includes/system-info.php
includes/validate.php

In most cases, using `else` is not required and the code can be cleaned-up by removing these.
In this PR I went through some of these and simplified the code where required.

Review usage of `} else {`

---

includes/classes/class-scans-stats.php

- Applied fix suggested by @jawadhere
- Updated to remove ternary

Fixes #379

---

includes/classes/class-rest-api.php
includes/enqueue-scripts.php
src/frontendHighlighterApp/index.js
src/frontendHighlighterApp/sass/app.scss

this PR sets the panel width to 400px only when it is visible

Fixes #430

---

admin/class-ajax.php
admin/class-frontend-highlight.php
admin/class-welcome-page.php
admin/class-widgets.php
includes/classes/class-rest-api.php
includes/helper-functions.php
includes/options-page.php
includes/system-info.php
includes/validate.php
partials/welcome-page.php
uninstall.php

This PR updates variable conversions to use casting.

Update functions to casting

---

includes/classes/class-enqueue-frontend.php

updated appCssUrl to prevent 404 error #455

---

admin/class-scans-stats.php

This PR fixes an incorrectly named variable.

461 scans status php deprecated

---

admin/class-welcome-page.php
admin/class-widgets.php
includes/helper-functions.php
partials/welcome-page.php
src/admin/sass/accessibility-checker-admin.scss

This PR fixes the heading order on the welcome screen.
Fixes: #478

Welcome Screen Heading Order

---

package.json
scripts/dist.sh

- replaces README.txt with readme.txt
- remove README.md
- adds changelog.txt

Updates dist script

---

admin/class-accessibility-statement.php
composer.lock
includes/activation.php

This PR moves the accessibility statement method to its own class.
- Created a new class that creates the accessibility statement on activation
- Removed custom database query that checked for existing accessibility statement and used `get_page_by_path()` instead
Fixes #469

Accessibility Statement Class

---

admin/class-welcome-page.php
partials/welcome-page.php

This PR adds missing UTM parameters to the welcome page URLs.
Fixes: #479

Welcome Page UTMs

---

src/frontendHighlighterApp/index.js

This PR fixes front end highlighter focus issue. 
Fixes #480

fixed - front end highlighter focus issue

---

.github/workflows/code-coverage-and-coveralls.yml
phpunit.dev.xml
phpunit.xml.dist

This workflow is triggered on `merge` into develop branch and PR created against `main` branch
* Runs phpunit with code coverage
* generates a html coverage report
* generates a clover style coverage report
* zips html report and uploads to the workflow run as an artefact
* converts clover report to coveralls style
* uploads coveralls report to coveralls service using workflow run token

Add coverage report workflow

---

.github/workflows/code-coverage-and-coveralls.yml

Also removes an unnecessary zip step since upload artefacts action already zips

Add coveralls-repo-toke

---

.github/workflows/wp-version-checker.yml

https://github.com/skaut/wordpress-version-checker

added - WordPress Version Checker workflow

---

includes/rules.php

Updates the copy of the rule title and sets the appropriate help link

Update the zooming and scaling user facing title and the help link

---

includes/rules.php

I done a spot check on all the summaries and it seems like just the initial one seen and the empty one was the only 2 that needed updated to match the sheet.
I also seen some typos when in here which I fixed.
Closes: #646

Sync summaries on rules from sheet

---

composer.json
composer.lock
src/admin/sass/accessibility-checker-admin.scss
src/common/sass/_variables.scss

This PR updates the styles on the plugin setting page.
- Updated settings styles
- Removed system information styles since the system information has been moved into the site health

Settings Styles

---

admin/class-scans-stats.php
admin/class-settings.php
includes/options-page.php

Some namespace updates were made in the pro plugins, this PR adds some checks to account for those and preserve back compat with pro plugins which do not get updated in tandem to the free plugin

Add some checks for namespace updates

---

src/admin/sass/accessibility-checker-admin.scss

This PR makes some tiny adjustments to the admin styles in the plugin:
* Removes redundant units
* Corrects some invalid properties
* Removes some overridden background-size properties inside the rules they are set in

Minor cleanup of admin styles

---

src/emailOptIn/modal.js

This prevents a JS error and will fail gracefully rather than producing any error a user would see or have issues because of it erroring.
Fixes: #721

Add a loop and retry for the email modal

---

accessibility-checker.php
admin/class-settings.php
package.json
readme.txt

Updates a condition wrapping a location that is checking for valid post types using legacy back compat code.

Hotfix: Release v1.15.2

---

includes/classes/Fixes/Fix/MetaViewportScalableFix.php
includes/classes/Fixes/FixesManager.php
src/frontendFixes/Fixes/metaViewportScalableFix.js
src/frontendFixes/index.js

Adds a fix that will ensure the meta viewport tag does not prevent user scaling.

Added: Fix for unscalable meta viewport tags

---

admin/AdminPage/FixesPage.php
admin/AdminPage/FixesSettingType/Checkbox.php
admin/AdminPage/FixesSettingType/Color.php
admin/AdminPage/FixesSettingType/Text.php
includes/classes/Fixes/Fix/CommentSearchLabelFix.php
includes/classes/Fixes/Fix/FocusOutlineFix.php
includes/classes/Fixes/Fix/HTMLLangAndDirFix.php
includes/classes/Fixes/Fix/LinkUnderline.php
includes/classes/Fixes/Fix/MetaViewportScalableFix.php
includes/classes/Fixes/Fix/PreventLinksOpeningNewWindowFix.php
includes/classes/Fixes/Fix/ReadMoreAddTitleFix.php
includes/classes/Fixes/Fix/RemoveTitleIfPrefferedAccessibleNameFix.php
includes/classes/Fixes/Fix/SkipLinkFix.php
includes/classes/Fixes/Fix/TabindexFix.php
includes/classes/Fixes/FixesManager.php

The PR updates the Fixes field labels and descriptions and some minor changes such as outline conditional.

Steve/no issue/focus outline conditional

---

includes/classes/Fixes/Fix/RemoveTitleIfPrefferedAccessibleNameFix.php

Updates the title to something more likely to be understood by users.

Use a more user friendly title for this fix

---

admin/AdminPage/FixesSettingType/Checkbox.php
admin/AdminPage/FixesSettingType/Text.php
admin/class-ajax.php
partials/custom-meta-box.php
src/common/sass/_fix-settings.scss
src/editorApp/index.js

This PR contains changes that were all minor so combined into a single PR.

Assorted bug fixes and tweaks for releases RC

---

src/common/sass/_fix-settings.scss
src/frontendHighlighterApp/sass/app.scss

This PR includes more style adjustments for the frontend highlighter modal
Basecamp card: https://3.basecamp.com/3579237/buckets/29333825/card_tables/cards/7923057011

More style tweaks to frontend highlighter fixes modal

---

includes/classes/Fixes/Fix/AddLabelToUnlabelledFormFieldsFix.php
includes/classes/Fixes/Fix/CommentSearchLabelFix.php
includes/classes/Fixes/Fix/FocusOutlineFix.php
includes/classes/Fixes/Fix/SkipLinkFix.php

This PR updates fix settings form labels and titles.

Steve/no issue/update fix labels

---

admin/class-admin-notices.php

Updates the date and value for the BF2024 notice to show

BF2024 date notice

---

accessibility-checker.php
package.json
readme.txt

Backport: Release/1.16.3

---

admin/class-welcome-page.php

The button currently points to an incorrect url since we changed it in a past release.

Update where a scan button link points to

---

includes/classes/class-rest-api.php

This endpoint exposes the site stats returned from `Scans_Stats()` class `summary()` method. This removes the need for the plugin to be activated in a site for one of the addon projects.

Add an endpoint to retrieve the site scan summary over a rest call

---

uninstall.php

I missed adding this key to the uninstall list when I added the fix.

Add new_window_warning fix key to the items cleared on uninstall

---

accessibility-checker.php
package.json
readme.txt

Backport: Release/1.19.0

---

accessibility-checker.php
package.json
readme.txt

Backport: Release/1.21.0

---

accessibility-checker.php
includes/helper-functions.php
package.json
readme.txt
src/frontendFixes/Fixes/metaViewportScalableFix.js
src/frontendFixes/Fixes/skipLinkFix.js

Hotfix release including:
This pull request includes several updates, including a version bump, enhancements to accessibility fixes, and a significant refactor of how upcoming meetup data is retrieved. Below is a categorized summary of the most important changes.
* Updated the plugin version to `1.22.1` in `accessibility-checker.php`, `package.json`, and `readme.txt` to reflect the new release. [[1]](diffhunk://#diff-350d3eed90dcfd8d1466cc7e406d1b17b604e284b62d478a7eb271cdd11287e7L13-R13) [[2]](diffhunk://#diff-350d3eed90dcfd8d1466cc7e406d1b17b604e284b62d478a7eb271cdd11287e7L38-R38) [[3]](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L3-R3) [[4]](diffhunk://#diff-9e6e4772050998a5c0dc3c61acf3dab0a7e594566171fa5746d6b62f9598efb6L5-R6)
* Improved the …

Hotfix: v1.22.1

---

src/pageScanner/index.js

This PR fixes an incorrect import directory in the scanner index file

Fix an incorrect import directory

---

.github/workflows/make-pot.yml

William/no issue/more changes to make pot workflow
